version: '2'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      DOCKER_USERNAME: username
      DOCKER_PASSWORD: password
    volumes:
      # REPLACE WITH PATH TO APP
      - /path/to/app/name/docker-compose.yml:/app/name
      # REPLACE WITH PATH TO APP
      - ./hooks.json:/etc/webhook/hooks.json
      - ./scripts:/opt/scripts
      - /var/run/docker.sock:/var/run/docker.sock
